# Generated by Django 3.0.7 on 2020-06-24 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appt_name', models.TextField(max_length=10, verbose_name='Select name of appt')),
                ('appt_date', models.DateTimeField(auto_now_add=True, verbose_name='Enter date of activity')),
                ('appt_duration', models.IntegerField(default=0, verbose_name='Enter duration in minutes')),
                ('appt_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
